### ISSUE TITLE
Mouse Idea

### ISSUE THREAD

**Issue by matthewtrainor1** [matthewtrainor1/ICS2OMTMH#4]
What we could do is put some colourful shapes for the kids to see instead of the normal mouse shape. So like a big red triangle, or a circle, or any shape. *we do this using mouseX & mouseY in place for le location of a shape*, so the mouse would still work as a mouse but we would see a shape instead.

**Comment by BeHappppy** [comment]
seems cool, I will work on the shape for mouse
